project:
  type: book
  output-dir: leitfaden_book

lang: de

book:
  title: "Wissenschaftliches Arbeiten"
  author: "Lehrstuhl | Juniorprofessur für Kommunikationswissenchaft"
  date: "last-modified"
  date-format: "DD.MM.YYYY"
  
  downloads: [pdf, epub]
  favicon: img/logo.svg
  repo-url: https://github.com/faucommsci/wissenschaftliches_arbeiten
  repo-actions: [issue]
  page-navigation: true
  
  page-footer:
    right: |
      Lehrstuhl & Juniorprofessur für Kommunikationswissenschaft
    left: |
      FAU Erlangen-Nürnberg, WiSo

  navbar:
    logo: leitfaden/img/fau_wiso_white.svg
    #background: "#04316a"
    #foreground: "#E6002E"
    search: true
    collapse: true
    border: true

    right:
      - icon: house
        href: https://www.kowi.rw.fau.de/
        aria-label: Home
      - icon: house-fill
        href: https://www.kommunikationswissenschaft.rw.fau.de/



  chapters:
    - index.qmd
    - part: Leitfaden
      chapters:
        - leitfaden/allgemeine_hinweise.qmd
        - leitfaden/abschlussarbeit.qmd
        - leitfaden/formalia.qmd
        - leitfaden/inhalte.qmd
        - leitfaden/literaturrecherche.qmd
        - leitfaden/open_science.qmd
        - leitfaden/zitieren.qmd
        - leitfaden/literatur.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - theme/theme.scss
    link-external-icon: True
    link-external-newwindow: True
    link-external-filter: '^(?:http|https):\/\/faucommsci.github.io'

  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex




