project:
  type: book

book:
  title: "Wissenschaftliches Arbeiten"
  author: "Lehrstuhl | Juniorprofessur für Kommunikationswissenchaft"
  date: "last-modified"
  date-format: "DD.MM.YYYY"
  downloads: [pdf, epub]
  favicon: img/logo.svg
  repo-actions: issue

  navbar:
    search: true
    collapse: true
    border: true
    tools:
      - icon: globe
        href: https://www.kommunikationswissenschaft.rw.fau.de
        text: Website des Lehrstuhls
      - icon: globe
        href: https://www.kommunikationswissenschaft.rw.fau.de/
        text: Website der Juniorprofessur


  chapters:
    - index.qmd
    - 01-allgemeine_hinweise.qmd
    - 02-ablauf.qmd
    - 03-formalia.qmd
    - 04-inhalte.qmd
    - 05-literaturrecherche.qmd
    - 06-open_science.qmd
    - 07-zitieren.qmd
    - 08-literatur.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  




