# Allgemeine Hinweise

## Hinweise zur Gültigkeit dieses Leitfadens

Der Leitfaden gilt für alle **Seminar-, Bachelor- und Abschlussarbeiten**, sofern nicht explizit anders angegeben. Sind Elemente des Leitfadens nicht auf das Format der Arbeit anwendbar, z. B. bei nicht-empirischen Arbeiten, Essays, u.Ä., gelten die übrigen anwendbaren Abschnitte.


## Zentrale Gütekriterien

Für studentische wissenschaftliche Arbeiten sind insbesondere die folgenden Kriterien relevant:

-   Einleitung und Zuschnitt des Themas für das gegebene oder gewählte Ziel

-   Recherche der relevanten Informationen in der Fachliteratur

-   Aufbereitung und gedankliche Durchdringung der Informationen

-   Erkenntnisgewinn der Arbeit

-   Darstellung in Text, Grafiken und Tabellen

-   Gestaltung anhand formaler Kriterien des wissenschaftlichen Arbeitens

Wie Sie diese Gütekriterien optimal erfüllen und eine erfolgreiche Abschluss- oder Seminararbeit am Lehrstuhl ablegen können, erfahren Sie in diesem Dokument. Bitte lesen Sie sich das Dokument daher aufmerksam vor der Erstellung Ihrer wissenschaftlichen Arbeit durch.

## Sprache

Wissenschaftliche Arbeiten am Lehrstuhl und der Juniorprofessur können grundsätzlich auf **Deutsch oder Englisch** geschrieben werden. Bitte beachten Sie zudem die Anweisungen im Seminar bzw. die Hinweise Ihrer Betreuer\*innen.

## Umfang, Schriftbild und Druck

Bachelorarbeiten sollten einen Umfang von etwa **8.000 -- 10.000 Wörtern** (ca. 30 Seiten), Masterarbeiten von etwa **18.000 -- 20.000 Wörtern** (ca. 60-70 Seiten) haben. Der Umfang von Seminararbeiten richtet sich nach den Vorgaben im jeweiligen Seminar, ist im Allgemeinen aber deutlich kürzer als bei Abschlussarbeiten. 

Deckblatt, Anhang, Verzeichnisse, Abbildungen, etc. zählen nicht in diese Begrenzung. Abbildungen und Tabellen sind im Text zu erwähnen und in der Nähe der Erwähnung, nicht im Anhang, zu platzieren. Tabellen und Abbildungen mit weiterführenden, nicht essenziellen Informationen oder Materialien können in den Anhang und müssen nicht im Text erwähnt werden.

Alle Abschlussarbeiten sind entweder in **Times New Roman 12pt** oder **Calibri 11pt** zu formatieren. Nutzen Sie für Fließtexte **2-fachen Zeilenabstand**.

Lassen Sie rechts und links einen Rand von 2.5-3cm. Fügen Sie in Kopf- oder Fußzeile Seitenzahlen und (kurz-)Titel ein.

Abschlussarbeiten müssen in **dreifacher Ausführung** beim Prüfungsamt abgegeben werden. Dabei müssen **zwei gedruckte** und gebundene Exemplare sowie **ein elektronisches Exemplar** (z. B. USB-Stick, CD) abgegeben werden.

## Einwilligungserklärung für Studienteilnehmende

Dieser Abschnitt ist für alle wissenschaftliche Arbeiten relevant, bei der Sie Daten von menschlichen Teilnehmenden erheben, z.B. Befragungen, Experiment, etc.

Wenn Sie Daten von Teilnehmenden erheben, benötigen Sie stets das Einverständnis aller Betroffenen. In der Einwilligungserklärung (Informed Consent) werden Teilnehmende über alle Vorteile, Risiken, Rechte und Datenschutz aufgeklärt. Dies kann z.B. am Anfang eines Online-Fragebogens oder in Papierform geschehen. Nur Personen, die vollständig aufgeklärt wurden und eingewilligt haben, dürfen an Studien teilnehmen. 

Sollte eine vollumfängliche Aufklärung über Inhalte, Zweck, oder genauen Ablauf der Studie im Vorhinein nicht möglich sein, z.B. bei einem doppelblinden Experiment, müssen Sie Teilnehmende immer im Nachhinein über die eigentlichen Inhalte/Zwecke/etc. aufklären (sog. Debriefing). Eine Auslassung von oder Täuschung über Inhalte, Zweck oder Ablauf der Studie sollten Sie stets mit der betreuenden Person absprechen. Vorteile, Risiken, Freiwilligkeit, Anonymität und Datenschutz, sowie Informationen zu den Studienverantwortlichen müssen *immer* vollständig und korrekt in der Einwilligkeitserklärung dargestellt werden. 

Im Folgenden finden Sie ein Beispiel für eine Einwilligungserklärung. Sie sollten die Erklärung stets auf die vorliegende Studie und aktuelle Gesetzeslage anpassen.

::: {#fig-consent fig-cap="Beispiel für eine Einwilligungserklärung" fig-align="left"}
::: box
<div>

​​{Titel der Studie}

Zweck der Studie: {Ziele der Studie kurz beschreiben}

Ablauf und Dauer: ​{Ablauf der Studie kurz beschreiben}​. Die Studie wird etwa ​{Minutenzahl} auswählen​ dauern. 

Vorteile und Risiken: Sie erhalten für die Teilnahme ​​{Belohnung angeben, sofern zutreffend}. ​Durch Ihre Teilnahme entstehen {keine Risiken, die über Risiken im alltäglichen Leben hinausgehen}. 

Freiwilligkeit: {Die Teilnahme an der Studie ist freiwillig und kann jederzeit und ohne Angabe von Gründen beendet werden, ohne dass Ihnen daraus Nachteile entstehen}. 

Anonymität und Datenschutz: {Die Erhebung Ihrer Daten erfolgt vollständig anonym, das heißt es ist kein Rückschluss auf Ihre Person möglich. Sie können Ihre Einwilligung in die Erhebung der Daten bis zum Ende der Studie widerrufen. Dafür tragen Sie einfach in das freie Textfeld am Ende ein, dass Ihre Daten gelöscht werden sollen. Nach Abschluss der Datenerhebung ist keine Löschung Ihres persönlichen Datensatzes möglich, da wir keine Zuordnung vornehmen können. ​Die Ergebnisse dieser Untersuchung werden für eine wissenschaftliche Publikation verwendet und als offene Daten gemäß den Empfehlungen der DFG im Open Science Framework Archiv zugänglich gemacht​. Dies dient der Qualitätssicherung wissenschaftlicher Forschung.} 

Die Erhebung der Daten erfolgt durch: 

​​{Abschlussarbeitskandidat:in/Seminarteilnehmerin}:​ ​{Vorname, Nachname Kandidat*in}.​ 

​​{Email Kandidat:in/Teilnehmer:in}.​ 

​​Betreuer:in:​ {Name Betreuer:in} 

​​{Email Betreuer:in} 

​​​FAU Erlangen-Nürnberg, Fachbereich Wirtschafts- und Sozialwissenschaften​​ 

{Lehrstuhl/​​Juniorprofessur} für Kommunikationswissenschaft​ 

​​Findelgasse 7/9, 90402 Nürnberg​ 

Verantwortung für die sachgemäße Datenverarbeitung trägt der/die Betreuer:in sowie ​​{Kandidat:in/Teilnehmer:in}​​. Sie dürfen eine Kopie dieser Erklärung herunterladen. 

Datenschutzbeauftragter: {Name}, {E-Mail}, {Tel.} 

Hiermit bestätige ich, dass… 

- ich über die Befragung informiert wurde und die Informationen verstanden habe, dass die die Teilnahme an dieser Studie freiwillig ist und ich die Studie jederzeit und ohne Angaben von Gründen beenden kann, ohne, dass mir daraus Nachteile entstehen 

- meine bereitgestellten Informationen in dieser Studie ​anonymisiert in wissenschaftlichen Artikeln und Präsentationen verwendet und mit anderen Forscherinnen und Forschern sowie in wissenschaftlichen Datenbanken ​ geteilt werden dürfen. 

​​◯ Ich bestätige und willige in die Befragung ein (an der Studie teilnehmen) 

​​◯​ Ich bestätige *nicht* und willige *nicht* in die Befragung ein (nicht teilnehmen) 
</div>
:::
:::

Hinweise: {Platzhalter} in @fig-consent durch entsprechende Inhalte ersetzen. Es handelt sich um Beispielformulierungen. Bitte nehmen Sie eine Anpassung auf die jeweilige Studie vor.
